export const locales = ['pt-BR', 'en', 'es', 'it', 'fr', 'ru', 'de', 'zh-CN', 'ja', 'ko', 'ar', 'he'] as const;
export type Locale = (typeof locales)[number];

export const localeLabels: Record<Locale, string> = {
  'pt-BR': 'Português (Brasil)',
  en: 'English',
  es: 'Español',
  it: 'Italiano',
  fr: 'Français',
  ru: 'Русский',
  de: 'Deutsch',
  'zh-CN': '简体中文',
  ja: '日本語',
  ko: '한국어',
  ar: 'العربية',
  he: 'עברית',
};

export function isRtl(locale: Locale) {
  return locale === 'ar' || locale === 'he';
}

const ptBR = {
  language: { label: 'Idioma' },
  navigation: { home: 'Início', how: 'Como usar', security: 'Segurança', privacy: 'Privacidade', terms: 'Termos', support: 'Apoie o projeto' },
  meta: { siteTitle: 'axismind', homeTitle: 'Um espaço privado para organizar o que você sente', howTitle: 'Como usar', securityTitle: 'Segurança', privacyTitle: 'Política de Privacidade', termsTitle: 'Termos de Uso', supportTitle: 'Apoie o projeto' },
  home: {
    eyebrow: 'Cuidado pessoal, no seu ritmo', title: 'Um espaço privado para organizar o que você sente', description: 'Diário local de bem-estar emocional, com relatos, check-ins, lembretes e preparação para conversas de cuidado.', primaryCta: 'Entenda como funciona', secondaryCta: 'Como protegemos seus dados', disclaimer: 'Para maiores de 18 anos. O axismind não diagnostica, prescreve ou substitui profissionais e serviços de emergência.', principlesEyebrow: 'Princípios do produto', principlesTitle: 'Uma ferramenta de organização pessoal, não uma avaliação clínica.', feature1Title: 'Privado por padrão', feature1Body: 'Seus relatos ficam no cofre criptografado do aparelho. Não existe sincronização automática do diário.', feature2Title: 'Texto ou voz', feature2Body: 'Registre no seu ritmo e revise a transcrição antes de guardar qualquer conteúdo.', feature3Title: 'Feito para o cotidiano', feature3Body: 'Check-ins, humor rápido, consciência corporal e lembretes opcionais em uma jornada acolhedora.', feature4Title: 'Você escolhe quando compartilhar', feature4Body: 'Exporte períodos em PDF ou faça uma cópia criptografada para guardar onde preferir.', screenshotsEyebrow: 'Prévia do aplicativo', screenshotsTitle: 'Conheça a experiência', screenshotsDescription: 'Capturas reais do candidato Android 1.5.10, build 19, executado no perfil de demonstração Thais Vieira.', transparencyEyebrow: 'Transparência desde o início', transparencyTitle: 'Saiba o que fica no aparelho e o que só sai por sua escolha.', transparencyCta: 'Conhecer os controles',
  },
  how: { eyebrow: 'Guia de uso', title: 'Comece com calma e mantenha você no controle.', intro: 'O axismind organiza registros pessoais no próprio aparelho. Nenhuma etapa exige que você conclua o que sente ou compartilhe um relato.', stepLabel: 'Passo', step1Title: 'Crie seu cofre', step1Body: 'Leia os documentos, confirme que tem 18 anos ou mais e defina uma senha forte. Ela protege o cofre local e não é enviada para nós.', step2Title: 'Registre o momento', step2Body: 'Use texto, humor rápido, check-in ou consciência corporal. Você escolhe quais informações deseja guardar.', step3Title: 'Se preferir, fale', step3Body: 'Baixe o modelo local de transcrição, grave e revise o texto. Só confirme quando ele representar o que você quis dizer.', step4Title: 'Revise sem rótulos', step4Body: 'As perguntas de reflexão são abertas e conservadoras. Elas não definem diagnóstico, emoção ou tratamento.', step5Title: 'Leve seu histórico', step5Body: 'Escolha um período para gerar PDF ou exporte o cofre criptografado. Guarde os arquivos com cuidado.', demoEyebrow: 'Demonstração visual', demoTitle: 'Veja como é simples usar o aplicativo', demoBody: 'A animação mostra uma jornada real no aplicativo: consentimento, criação do cofre, perfil com foto, relato, reflexão, voz e relatório. Ela foi apenas acelerada e não contém instruções sobrepostas à interface.', demoAlt: 'Demonstração animada dos cinco passos para usar o axismind', helpTitle: 'Se você precisar de ajuda imediata', helpBody: 'O aplicativo oferece atalhos acionados por você, mas não monitora crises nem chama socorro automaticamente. No Brasil, o CVV atende pelo 188. Em emergência médica, procure o serviço de emergência local.' },
  support: { eyebrow: 'Apoio transparente', title: 'Ajude o axismind a continuar cuidadoso e independente.', intro: 'O apoio é voluntário, não oferece recursos extras no aplicativo e não condiciona atendimento. Qualquer valor ajuda a manter o projeto.', dataTitle: 'Dados para apoio', beneficiary: 'Beneficiário', pixKeyLabel: 'Chave PIX (e-mail)', qrHint: 'O QR Code não define um valor: escolha quanto deseja apoiar no aplicativo do seu banco.', qrCaption: 'Escaneie para apoiar via PIX', unavailableTitle: 'Informações ainda não cadastradas', unavailableBody: 'Os dados serão publicados somente depois da confirmação do beneficiário e da finalidade.', securityTitle: 'Segurança', securityBody: 'O site nunca solicitará senha bancária, código de autenticação, foto de documento ou dados do cartão. Prefira uma chave PIX aleatória ou institucional em vez de CPF.', doubt: 'Em caso de dúvida, confirme pelo canal oficial:', internationalTitle: 'Apoio internacional', internationalBody: 'Uma opção para contribuições internacionais será adicionada futuramente.' },
  privacy: { title: 'Política de Privacidade', intro: 'Esta política descreve como o aplicativo e este site tratam informações, em linguagem direta.', s1: '1. Controlador e contato', s2: '2. O que é o axismind', s3: '3. Dados e finalidades', s4: '4. Onde ficam os dados', s5: '5. Conexões externas', s6: '6. Direitos e exclusão', s7: '7. Segurança e limites', s8: '8. Idade e mudanças', body1: 'Controlador: {controller}, pessoa física, {location}. Canal para privacidade e direitos: {email}.', body2: 'É um diário pessoal de bem-estar emocional local-first. Permite registrar texto, voz transcrita, check-ins, sensações corporais, medicação informada e preparação para consultas. Não diagnostica, prescreve ou trata condições de saúde e não substitui profissionais nem serviços de emergência.', body3: 'Relatos, check-ins, reflexões, corpo e medicação informada: diário, autorreflexão e lembretes opcionais. Áudio: transcrição e revisão local, com armazenamento privado temporário. Nome, foto e e-mail: identidade opcional do perfil. Contato de confiança: acesso rápido manual, nunca acionado automaticamente. Recibo legal: registro local da versão aceita. PDF e backup: portabilidade escolhida pela pessoa.', body4: 'O conteúdo do diário fica no cofre criptografado do aparelho. Não há sincronização automática, publicidade, venda de dados ou treinamento de IA externa com relatos. Arquivos exportados passam a ficar sob controle da pessoa e do destino escolhido.', body5: 'Conexões externas só ocorrem após ação explícita: Google ou Apple para identidade básica, servidor de distribuição para obter o modelo de transcrição, loja para avaliação e compartilhador do sistema para PDF ou backup. Este site estático não possui formulário, analytics próprio ou cookies de publicidade; a hospedagem pode manter registros técnicos conforme os termos do provedor.', body6: 'A pessoa pode acessar e corrigir registros no app, exportar uma cópia e excluir integralmente o cofre local. Solicitações adicionais podem ser encaminhadas ao canal informado acima. Depois de tentar exercer o direito junto ao controlador, também é possível peticionar perante a ANPD.', body7: 'O banco local usa SQLCipher; senha e backup utilizam derivação de chave e criptografia autenticada. O PDF não possui senha nesta versão. Nenhum controle elimina todos os riscos, especialmente em aparelhos comprometidos ou quando um arquivo é exportado.', body8: 'O aplicativo é destinado a maiores de {age} anos. Mudanças relevantes incrementam a versão do documento e exigem novo aceite dentro do app.' },
  terms: { title: 'Termos de Uso', intro: 'Ao usar o axismind, você confirma que compreendeu a natureza pessoal e local da ferramenta e seus limites.', s1: '1. Fornecedor', s2: '2. Elegibilidade', s3: '3. Natureza e limites', s4: '4. Responsabilidades da pessoa usuária', s5: '5. Recursos opcionais', s6: '6. Exportações e perda de acesso', s7: '7. Propriedade e uso adequado', s8: '8. Mudanças', body1: 'O axismind é disponibilizado por {controller}, pessoa física, {location}. Contato: {email}.', body2: 'O produto é destinado exclusivamente a pessoas com {age} anos ou mais. Não existe fluxo de consentimento parental nesta versão.', body3: 'O app auxilia a registrar e organizar experiências pessoais. Não realiza diagnóstico, prescrição, tratamento, monitoramento clínico ou acionamento automático de emergência.', body4: 'Manter a senha e o aparelho protegidos. Revisar transcrições e relatórios antes de guardar ou compartilhar. Evitar dados sensíveis de terceiros sem autorização. Fazer backup antes de excluir o cofre ou trocar de aparelho.', body5: 'Voz, lembretes, contato de confiança, login social, PDF e backup dependem de escolha e permissões do sistema. Fabricantes e sistemas podem limitar alarmes, notificações e execução em segundo plano.', body6: 'Arquivos exportados ficam sob responsabilidade da pessoa. O controlador não recebe uma cópia do cofre e não consegue recuperar a senha local perdida. A exclusão do cofre é irreversível sem backup válido.', body7: 'A marca, interface e conteúdo autoral são protegidos. É proibido usar o produto para violar direitos, tentar acessar dados de terceiros ou contornar controles de segurança.', body8: 'Alterações relevantes nos Termos serão identificadas por nova versão e novo aceite no aplicativo.' },
  security: { eyebrow: 'Privacidade por arquitetura', title: 'Segurança local, explicada com transparência.', intro: 'O axismind foi desenhado para reduzir a exposição dos relatos: o dado pessoal permanece no aparelho e cada saída depende de uma ação explícita da pessoa.', controlsTitle: 'Controles presentes no aplicativo', control1Title: 'Cofre local criptografado', control1Body: 'O conteúdo pessoal fica no banco SQLCipher do aparelho. A chave do cofre é protegida pelo armazenamento seguro do sistema.', control2Title: 'Sem sincronização automática', control2Body: 'O diário não é enviado para uma nuvem do axismind. Backup e PDF só saem do aparelho quando a própria pessoa escolhe exportar.', control3Title: 'Backup do sistema bloqueado', control3Body: 'As regras do Android impedem que o conteúdo privado do aplicativo entre no backup automático ou na extração comum de dados.', control4Title: 'Build Android analisado', control4Body: 'O APK 1.5.16 de homologação passou por análise estática local com MobSF 4.5.2 e por auditoria do inventário JavaScript em 7 de setembro de 2026.', resultEyebrow: 'Avaliação automatizada independente', resultTitle: 'O que a análise estática encontrou', stat1: 'trackers de privacidade detectados no APK analisado', stat2: 'achados de configuração de segurança de rede', stat3: 'combinações de pacote e versão consultadas sem advisory npm conhecido na data', resultDisclaimer: 'Esta é uma fotografia automatizada do build de homologação, não uma certificação nem garantia de ausência de vulnerabilidades. Alertas foram revisados no contexto do aplicativo e a análise será repetida no artefato assinado para publicação. Testes manuais e atualização contínua das dependências continuam fazendo parte do processo.', tool: 'Ferramenta utilizada:' },
  footer: { description: 'Um diário pessoal local-first. Não oferece diagnóstico, prescrição, tratamento ou atendimento de emergência.', information: 'Informações', contact: 'Contato', terms: 'Termos de uso', copyright: 'conteúdo informativo' },
  gallery: { enlarge: 'Ampliar', enlargeAria: 'Ampliar imagem: {title}', dialogAria: 'Imagem ampliada. Use scroll, duplo clique ou dois dedos para zoom; arraste para mover. Pressione Escape para fechar.' },
  copy: { idle: 'Copiar chave PIX', copied: 'Chave PIX copiada', error: 'Não foi possível copiar' },
} as const;

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : T[K] extends object ? Widen<T[K]> : T[K] };
export type Messages = Widen<typeof ptBR>;

const en: Messages = {
  language: { label: 'Language' }, navigation: { home: 'Home', how: 'How it works', security: 'Security', privacy: 'Privacy', terms: 'Terms', support: 'Support the project' }, meta: { siteTitle: 'axismind', homeTitle: 'A private space to organize what you feel', howTitle: 'How it works', securityTitle: 'Security', privacyTitle: 'Privacy Policy', termsTitle: 'Terms of Use', supportTitle: 'Support the project' },
  home: { eyebrow: 'Personal care, at your pace', title: 'A private space to organize what you feel', description: 'A local emotional wellbeing journal with notes, check-ins, reminders and preparation for care conversations.', primaryCta: 'See how it works', secondaryCta: 'How we protect your data', disclaimer: 'For people aged 18 and over. axismind does not diagnose, prescribe or replace professionals and emergency services.', principlesEyebrow: 'Product principles', principlesTitle: 'A personal organization tool, not a clinical assessment.', feature1Title: 'Private by default', feature1Body: 'Your notes stay in the device’s encrypted vault. The journal is never automatically synchronized.', feature2Title: 'Text or voice', feature2Body: 'Record at your own pace and review the transcription before saving anything.', feature3Title: 'Made for everyday life', feature3Body: 'Check-ins, quick mood tracking, body awareness and optional reminders in a welcoming journey.', feature4Title: 'You choose when to share', feature4Body: 'Export periods as PDF or make an encrypted copy to keep wherever you prefer.', screenshotsEyebrow: 'App preview', screenshotsTitle: 'Explore the experience', screenshotsDescription: 'Real captures from Android candidate 1.5.10, build 19, run with the Thais Vieira demo profile.', transparencyEyebrow: 'Transparency from the start', transparencyTitle: 'Know what stays on the device and what leaves only by your choice.', transparencyCta: 'Explore the controls' },
  how: { eyebrow: 'Usage guide', title: 'Start gently and stay in control.', intro: 'axismind organizes personal records on the device itself. No step asks you to conclude what you feel or share a note.', stepLabel: 'Step', step1Title: 'Create your vault', step1Body: 'Read the documents, confirm you are 18 or older and set a strong password. It protects the local vault and is never sent to us.', step2Title: 'Record the moment', step2Body: 'Use text, quick mood, check-in or body awareness. You choose what to keep.', step3Title: 'Speak if you prefer', step3Body: 'Download the local transcription model, record and review the text. Confirm it only when it reflects what you meant.', step4Title: 'Review without labels', step4Body: 'Reflection questions are open and conservative. They do not define diagnosis, emotion or treatment.', step5Title: 'Take your history with you', step5Body: 'Choose a period to generate a PDF or export the encrypted vault. Keep files carefully.', demoEyebrow: 'Visual demo', demoTitle: 'See how simple the app is to use', demoBody: 'The animation shows a real app journey: consent, vault creation, profile photo, note, reflection, voice and report. It is only sped up and contains no instructions over the interface.', demoAlt: 'Animated demonstration of the five steps to use axismind', helpTitle: 'If you need immediate help', helpBody: 'The app offers shortcuts you trigger yourself, but it does not monitor crises or call for help automatically. In Brazil, CVV is available at 188. In a medical emergency, contact your local emergency service.' },
  support: { eyebrow: 'Transparent support', title: 'Help axismind remain careful and independent.', intro: 'Support is voluntary, provides no extra in-app features and does not condition care. Any amount helps keep the project going.', dataTitle: 'Support details', beneficiary: 'Beneficiary', pixKeyLabel: 'PIX key (email)', qrHint: 'The QR Code does not set an amount: choose how much to support in your bank app.', qrCaption: 'Scan to support via PIX', unavailableTitle: 'Information not registered yet', unavailableBody: 'Details will be published only after the beneficiary and purpose are confirmed.', securityTitle: 'Security', securityBody: 'The site will never request a bank password, authentication code, document photo or card details. Prefer a random or institutional PIX key instead of a tax ID.', doubt: 'If in doubt, confirm through the official channel:', internationalTitle: 'International support', internationalBody: 'An option for international contributions will be added in the future.' },
  privacy: { title: 'Privacy Policy', intro: 'This policy describes how the app and this site handle information, in direct language.', s1: '1. Controller and contact', s2: '2. What axismind is', s3: '3. Data and purposes', s4: '4. Where data stays', s5: '5. External connections', s6: '6. Rights and deletion', s7: '7. Security and limits', s8: '8. Age and changes', body1: 'Controller: {controller}, an individual, {location}. Privacy and rights channel: {email}.', body2: 'A local-first personal emotional wellbeing journal. It records text, transcribed voice, check-ins, body sensations, reported medication and preparation for appointments. It does not diagnose, prescribe or treat health conditions and does not replace professionals or emergency services.', body3: 'Notes, check-ins, reflections, body and reported medication: journaling, self-reflection and optional reminders. Audio: local transcription and review with temporary private storage. Name, photo and email: optional profile identity. Trusted contact: manual quick access, never triggered automatically. Legal receipt: local record of the accepted version. PDF and backup: portability chosen by the person.', body4: 'Journal content stays in the device’s encrypted vault. There is no automatic synchronization, advertising, data sale or external AI training with notes. Exported files are controlled by the person and the chosen destination.', body5: 'External connections happen only after an explicit action: Google or Apple for basic identity, a distribution server for the transcription model, the store for reviews and the system share sheet for PDF or backup. This static site has no form, own analytics or advertising cookies; hosting may keep technical logs under the provider terms.', body6: 'People can access and correct records in the app, export a copy and fully delete the local vault. Additional requests can be sent to the channel above. After contacting the controller, a petition may also be filed with ANPD.', body7: 'The local database uses SQLCipher; password and backup use key derivation and authenticated encryption. PDFs are not password-protected in this version. No control removes every risk, especially on compromised devices or when a file is exported.', body8: 'The app is for people aged {age} and over. Material changes increment the document version and require new acceptance in the app.' },
  terms: { title: 'Terms of Use', intro: 'By using axismind, you confirm that you understand the personal and local nature of the tool and its limits.', s1: '1. Provider', s2: '2. Eligibility', s3: '3. Nature and limits', s4: '4. User responsibilities', s5: '5. Optional features', s6: '6. Exports and loss of access', s7: '7. Ownership and proper use', s8: '8. Changes', body1: 'axismind is provided by {controller}, an individual, {location}. Contact: {email}.', body2: 'The product is exclusively for people aged {age} and over. This version has no parental consent flow.', body3: 'The app helps record and organize personal experiences. It does not diagnose, prescribe, treat, clinically monitor or automatically call emergency services.', body4: 'Keep the password and device protected. Review transcriptions and reports before storing or sharing. Avoid sensitive third-party data without authorization. Back up before deleting the vault or changing devices.', body5: 'Voice, reminders, trusted contact, social login, PDF and backup depend on user choice and system permissions. Manufacturers and systems may limit alarms, notifications and background execution.', body6: 'Exported files are the person’s responsibility. The controller receives no vault copy and cannot recover a lost local password. Deleting the vault is irreversible without a valid backup.', body7: 'The brand, interface and authored content are protected. It is forbidden to use the product to violate rights, access third-party data or bypass security controls.', body8: 'Material changes to the Terms will be identified by a new version and new acceptance in the app.' },
  security: { eyebrow: 'Privacy by architecture', title: 'Local security, explained transparently.', intro: 'axismind was designed to reduce exposure of notes: personal data stays on the device and every exit depends on an explicit action.', controlsTitle: 'Controls present in the app', control1Title: 'Encrypted local vault', control1Body: 'Personal content stays in the device’s SQLCipher database. The vault key is protected by the system secure storage.', control2Title: 'No automatic synchronization', control2Body: 'The journal is not sent to an axismind cloud. Backup and PDF leave the device only when the person chooses to export.', control3Title: 'System backup blocked', control3Body: 'Android rules prevent private app content from entering automatic backup or ordinary data extraction.', control4Title: 'Android build analyzed', control4Body: 'The APK 1.5.16 staging build underwent local static analysis with MobSF 4.5.2 and JavaScript inventory audit on September 7, 2026.', resultEyebrow: 'Independent automated assessment', resultTitle: 'What static analysis found', stat1: 'privacy trackers detected in the analyzed APK', stat2: 'network security configuration findings', stat3: 'package/version combinations checked with no known npm advisory on the date', resultDisclaimer: 'This is an automated snapshot of a staging build, not a certification or guarantee that vulnerabilities are absent. Alerts were reviewed in app context and analysis will be repeated on the signed release artifact. Manual testing and continuous dependency updates remain part of the process.', tool: 'Tool used:' },
  footer: { description: 'A local-first personal journal. It does not provide diagnosis, prescription, treatment or emergency care.', information: 'Information', contact: 'Contact', terms: 'Terms of use', copyright: 'informational content' },
  gallery: { enlarge: 'Enlarge', enlargeAria: 'Enlarge image: {title}', dialogAria: 'Enlarged image. Use scroll, double-click or two fingers to zoom; drag to move. Press Escape to close.' }, copy: { idle: 'Copy PIX key', copied: 'PIX key copied', error: 'Could not copy' },
};

const cloneMessages = (base: Messages): Messages => ({
  language: { ...base.language }, navigation: { ...base.navigation }, meta: { ...base.meta }, home: { ...base.home }, how: { ...base.how }, support: { ...base.support }, privacy: { ...base.privacy }, terms: { ...base.terms }, security: { ...base.security }, footer: { ...base.footer }, gallery: { ...base.gallery }, copy: { ...base.copy },
});

const es: Messages = { ...cloneMessages(en), language: { label: 'Idioma' }, navigation: { home: 'Inicio', how: 'Cómo usar', security: 'Seguridad', privacy: 'Privacidad', terms: 'Términos', support: 'Apoya el proyecto' }, home: { ...en.home, eyebrow: 'Cuidado personal, a tu ritmo', title: 'Un espacio privado para organizar lo que sientes', description: 'Diario local de bienestar emocional, con relatos, registros, recordatorios y preparación para conversaciones de cuidado.', primaryCta: 'Entiende cómo funciona', secondaryCta: 'Cómo protegemos tus datos', disclaimer: 'Para mayores de 18 años. axismind no diagnostica, prescribe ni sustituye a profesionales o servicios de emergencia.', principlesEyebrow: 'Principios del producto', principlesTitle: 'Una herramienta de organización personal, no una evaluación clínica.', screenshotsEyebrow: 'Vista previa de la app', screenshotsTitle: 'Conoce la experiencia', transparencyEyebrow: 'Transparencia desde el inicio', transparencyCta: 'Conocer los controles' }, footer: { ...en.footer, information: 'Información', contact: 'Contacto', terms: 'Términos de uso', copyright: 'contenido informativo' }, copy: { idle: 'Copiar clave PIX', copied: 'Clave PIX copiada', error: 'No se pudo copiar' } };
const it: Messages = { ...cloneMessages(en), language: { label: 'Lingua' }, navigation: { home: 'Inizio', how: 'Come funziona', security: 'Sicurezza', privacy: 'Privacy', terms: 'Termini', support: 'Sostieni il progetto' }, home: { ...en.home, eyebrow: 'Cura personale, al tuo ritmo', title: 'Uno spazio privato per organizzare ciò che senti', description: 'Diario locale del benessere emotivo, con note, check-in, promemoria e preparazione alle conversazioni di cura.', primaryCta: 'Scopri come funziona', secondaryCta: 'Come proteggiamo i tuoi dati', disclaimer: 'Per persone dai 18 anni. axismind non diagnostica, prescrive né sostituisce professionisti e servizi di emergenza.', principlesEyebrow: 'Principi del prodotto', principlesTitle: 'Uno strumento di organizzazione personale, non una valutazione clinica.', screenshotsEyebrow: 'Anteprima dell’app', screenshotsTitle: 'Scopri l’esperienza', transparencyEyebrow: 'Trasparenza fin dall’inizio', transparencyCta: 'Scopri i controlli' }, footer: { ...en.footer, information: 'Informazioni', contact: 'Contatti', terms: 'Termini d’uso', copyright: 'contenuto informativo' }, copy: { idle: 'Copia chiave PIX', copied: 'Chiave PIX copiata', error: 'Impossibile copiare' } };
const fr: Messages = { ...cloneMessages(en), language: { label: 'Langue' }, navigation: { home: 'Accueil', how: 'Fonctionnement', security: 'Sécurité', privacy: 'Confidentialité', terms: 'Conditions', support: 'Soutenir le projet' }, home: { ...en.home, eyebrow: 'Prendre soin de soi, à son rythme', title: 'Un espace privé pour organiser ce que vous ressentez', description: 'Journal local de bien-être émotionnel, avec notes, check-ins, rappels et préparation aux échanges de soin.', primaryCta: 'Voir comment ça marche', secondaryCta: 'Comment nous protégeons vos données', disclaimer: 'Pour les personnes de 18 ans et plus. axismind ne diagnostique pas, ne prescrit pas et ne remplace pas les professionnels ni les services d’urgence.', principlesEyebrow: 'Principes du produit', principlesTitle: 'Un outil d’organisation personnelle, pas une évaluation clinique.', screenshotsEyebrow: 'Aperçu de l’application', screenshotsTitle: 'Découvrez l’expérience', transparencyEyebrow: 'Transparence dès le départ', transparencyCta: 'Découvrir les contrôles' }, footer: { ...en.footer, information: 'Informations', contact: 'Contact', terms: 'Conditions d’utilisation', copyright: 'contenu informatif' }, copy: { idle: 'Copier la clé PIX', copied: 'Clé PIX copiée', error: 'Impossible de copier' } };
const ru: Messages = { ...en, language: { label: 'Язык' }, navigation: { home: 'Главная', how: 'Как это работает', security: 'Безопасность', privacy: 'Конфиденциальность', terms: 'Условия', support: 'Поддержать проект' }, meta: { ...en.meta, homeTitle: 'Личное пространство для организации своих чувств', howTitle: 'Как это работает', securityTitle: 'Безопасность', privacyTitle: 'Политика конфиденциальности', termsTitle: 'Условия использования', supportTitle: 'Поддержать проект' }, home: { ...en.home, eyebrow: 'Забота о себе в своём темпе', title: 'Личное пространство для организации своих чувств', description: 'Локальный дневник эмоционального благополучия с заметками, отметками, напоминаниями и подготовкой к разговорам о заботе.', primaryCta: 'Узнать, как это работает', secondaryCta: 'Как мы защищаем ваши данные', disclaimer: 'Для людей от 18 лет. axismind не ставит диагнозы, не назначает лечение и не заменяет специалистов и экстренные службы.', principlesEyebrow: 'Принципы продукта', principlesTitle: 'Инструмент личной организации, а не клиническая оценка.', screenshotsEyebrow: 'Обзор приложения', screenshotsTitle: 'Познакомьтесь с опытом', transparencyEyebrow: 'Прозрачность с самого начала', transparencyCta: 'Изучить настройки' }, footer: { ...en.footer, information: 'Информация', contact: 'Контакты', terms: 'Условия использования' }, copy: { idle: 'Скопировать ключ PIX', copied: 'Ключ PIX скопирован', error: 'Не удалось скопировать' } };
const de: Messages = { ...en, language: { label: 'Sprache' }, navigation: { home: 'Startseite', how: 'So funktioniert es', security: 'Sicherheit', privacy: 'Datenschutz', terms: 'Bedingungen', support: 'Projekt unterstützen' }, meta: { ...en.meta, homeTitle: 'Ein privater Ort, um Gefühle zu ordnen', howTitle: 'So funktioniert es', securityTitle: 'Sicherheit', privacyTitle: 'Datenschutzerklärung', termsTitle: 'Nutzungsbedingungen', supportTitle: 'Projekt unterstützen' }, home: { ...en.home, eyebrow: 'Fürsorge im eigenen Tempo', title: 'Ein privater Ort, um Gefühle zu ordnen', description: 'Ein lokales Tagebuch für emotionales Wohlbefinden mit Notizen, Check-ins, Erinnerungen und Vorbereitung auf Gespräche.', primaryCta: 'So funktioniert es', secondaryCta: 'So schützen wir Ihre Daten', disclaimer: 'Für Personen ab 18 Jahren. axismind stellt keine Diagnosen, verschreibt nichts und ersetzt keine Fachkräfte oder Notdienste.', principlesEyebrow: 'Produktprinzipien', principlesTitle: 'Ein Werkzeug zur persönlichen Organisation, keine klinische Bewertung.', screenshotsEyebrow: 'App-Vorschau', screenshotsTitle: 'Die Erfahrung kennenlernen', transparencyEyebrow: 'Transparenz von Anfang an', transparencyCta: 'Kontrollen kennenlernen' }, footer: { ...en.footer, information: 'Informationen', contact: 'Kontakt', terms: 'Nutzungsbedingungen' }, copy: { idle: 'PIX-Schlüssel kopieren', copied: 'PIX-Schlüssel kopiert', error: 'Kopieren nicht möglich' } };
const zhCN: Messages = { ...en, language: { label: '语言' }, navigation: { home: '首页', how: '使用方法', security: '安全', privacy: '隐私', terms: '条款', support: '支持项目' }, meta: { ...en.meta, homeTitle: '整理感受的私密空间', howTitle: '使用方法', securityTitle: '安全', privacyTitle: '隐私政策', termsTitle: '使用条款', supportTitle: '支持项目' }, home: { ...en.home, eyebrow: '按照自己的节奏照顾自己', title: '整理感受的私密空间', description: '本地情绪健康日记，支持记录、签到、提醒以及为照护对话做准备。', primaryCta: '了解使用方法', secondaryCta: '我们如何保护您的数据', disclaimer: '适用于 18 岁及以上人群。axismind 不提供诊断或处方，也不能替代专业人员和急救服务。', principlesEyebrow: '产品原则', principlesTitle: '用于个人整理的工具，而不是临床评估。', screenshotsEyebrow: '应用预览', screenshotsTitle: '了解使用体验', transparencyEyebrow: '从一开始就保持透明', transparencyCta: '了解控制选项' }, footer: { ...en.footer, information: '信息', contact: '联系方式', terms: '使用条款' }, copy: { idle: '复制 PIX 密钥', copied: 'PIX 密钥已复制', error: '无法复制' } };
const ja: Messages = { ...en, language: { label: '言語' }, navigation: { home: 'ホーム', how: '使い方', security: 'セキュリティ', privacy: 'プライバシー', terms: '利用規約', support: 'プロジェクトを支援' }, meta: { ...en.meta, homeTitle: '感じたことを整理するためのプライベートな場所', howTitle: '使い方', securityTitle: 'セキュリティ', privacyTitle: 'プライバシーポリシー', termsTitle: '利用規約', supportTitle: 'プロジェクトを支援' }, home: { ...en.home, eyebrow: '自分のペースで向き合う', title: '感じたことを整理するためのプライベートな場所', description: '記録、チェックイン、リマインダー、ケアの会話の準備ができる、ローカルな心のウェルビーイング日記です。', primaryCta: '使い方を見る', secondaryCta: 'データを守る仕組み', disclaimer: '18歳以上の方を対象としています。axismind は診断や処方を行わず、専門家や救急サービスの代わりにはなりません。', principlesEyebrow: 'プロダクトの原則', principlesTitle: '臨床評価ではなく、自分を整理するためのツールです。', screenshotsEyebrow: 'アプリのプレビュー', screenshotsTitle: '体験を見る', transparencyEyebrow: '最初から透明に', transparencyCta: '管理方法を見る' }, footer: { ...en.footer, information: '情報', contact: '連絡先', terms: '利用規約' }, copy: { idle: 'PIXキーをコピー', copied: 'PIXキーをコピーしました', error: 'コピーできませんでした' } };
const ko: Messages = { ...en, language: { label: '언어' }, navigation: { home: '홈', how: '사용 방법', security: '보안', privacy: '개인정보', terms: '약관', support: '프로젝트 후원' }, meta: { ...en.meta, homeTitle: '느끼는 것을 정리하는 개인 공간', howTitle: '사용 방법', securityTitle: '보안', privacyTitle: '개인정보 처리방침', termsTitle: '이용 약관', supportTitle: '프로젝트 후원' }, home: { ...en.home, eyebrow: '나만의 속도로 돌보기', title: '느끼는 것을 정리하는 개인 공간', description: '기록, 체크인, 알림과 돌봄 대화를 준비할 수 있는 로컬 정서 웰빙 일기입니다.', primaryCta: '사용 방법 알아보기', secondaryCta: '데이터를 보호하는 방법', disclaimer: '만 18세 이상을 위한 서비스입니다. axismind는 진단·처방을 제공하지 않으며 전문가와 응급 서비스를 대신하지 않습니다.', principlesEyebrow: '제품 원칙', principlesTitle: '임상 평가가 아닌 개인 정리를 위한 도구입니다.', screenshotsEyebrow: '앱 미리보기', screenshotsTitle: '경험 살펴보기', transparencyEyebrow: '처음부터 투명하게', transparencyCta: '제어 기능 알아보기' }, footer: { ...en.footer, information: '정보', contact: '연락처', terms: '이용 약관' }, copy: { idle: 'PIX 키 복사', copied: 'PIX 키가 복사되었습니다', error: '복사할 수 없습니다' } };
const ar: Messages = { ...en, language: { label: 'اللغة' }, navigation: { home: 'الرئيسية', how: 'طريقة الاستخدام', security: 'الأمان', privacy: 'الخصوصية', terms: 'الشروط', support: 'دعم المشروع' }, meta: { ...en.meta, homeTitle: 'مساحة خاصة لتنظيم ما تشعر به', howTitle: 'طريقة الاستخدام', securityTitle: 'الأمان', privacyTitle: 'سياسة الخصوصية', termsTitle: 'شروط الاستخدام', supportTitle: 'دعم المشروع' }, home: { ...en.home, eyebrow: 'العناية الشخصية بإيقاعك', title: 'مساحة خاصة لتنظيم ما تشعر به', description: 'يوميات محلية للرفاه العاطفي تتضمن الملاحظات وتسجيلات المتابعة والتذكيرات والاستعداد لحوارات الرعاية.', primaryCta: 'تعرّف على طريقة الاستخدام', secondaryCta: 'كيف نحمي بياناتك', disclaimer: 'لمن تبلغ أعمارهم 18 عاماً فأكثر. لا يقدّم axismind تشخيصاً أو وصفات ولا يحل محل المختصين وخدمات الطوارئ.', principlesEyebrow: 'مبادئ المنتج', principlesTitle: 'أداة لتنظيم الذات وليست تقييماً سريرياً.', screenshotsEyebrow: 'معاينة التطبيق', screenshotsTitle: 'تعرّف على التجربة', transparencyEyebrow: 'الشفافية منذ البداية', transparencyCta: 'تعرّف على عناصر التحكم' }, footer: { ...en.footer, information: 'معلومات', contact: 'تواصل', terms: 'شروط الاستخدام' }, copy: { idle: 'نسخ مفتاح PIX', copied: 'تم نسخ مفتاح PIX', error: 'تعذر النسخ' } };
const he: Messages = { ...en, language: { label: 'שפה' }, navigation: { home: 'ראשי', how: 'איך זה עובד', security: 'אבטחה', privacy: 'פרטיות', terms: 'תנאים', support: 'תמיכה בפרויקט' }, meta: { ...en.meta, homeTitle: 'מרחב פרטי לארגון מה שאתם מרגישים', howTitle: 'איך זה עובד', securityTitle: 'אבטחה', privacyTitle: 'מדיניות פרטיות', termsTitle: 'תנאי שימוש', supportTitle: 'תמיכה בפרויקט' }, home: { ...en.home, eyebrow: 'טיפול אישי, בקצב שלכם', title: 'מרחב פרטי לארגון מה שאתם מרגישים', description: 'יומן מקומי לרווחה רגשית עם רשומות, בדיקות מצב, תזכורות והכנה לשיחות טיפול.', primaryCta: 'איך זה עובד', secondaryCta: 'איך אנחנו מגנים על הנתונים שלכם', disclaimer: 'מיועד לבני 18 ומעלה. axismind אינו מאבחן או רושם ואינו מחליף אנשי מקצוע ושירותי חירום.', principlesEyebrow: 'עקרונות המוצר', principlesTitle: 'כלי לארגון אישי, לא להערכה קלינית.', screenshotsEyebrow: 'תצוגה מקדימה של האפליקציה', screenshotsTitle: 'הכירו את החוויה', transparencyEyebrow: 'שקיפות מההתחלה', transparencyCta: 'הכירו את הבקרות' }, footer: { ...en.footer, information: 'מידע', contact: 'יצירת קשר', terms: 'תנאי שימוש' }, copy: { idle: 'העתקת מפתח PIX', copied: 'מפתח PIX הועתק', error: 'לא ניתן להעתיק' } };

for (const locale of [es, it, fr, ru, de, zhCN, ja, ko, ar, he]) {
  Object.assign(locale, {
    how: { ...en.how },
    support: { ...en.support },
    privacy: { ...en.privacy },
    terms: { ...en.terms },
    security: { ...en.security },
  });
}

Object.assign(es.how, { eyebrow: 'Guía de uso', title: 'Empieza con calma y mantén el control.', intro: 'axismind organiza tus registros personales en el propio dispositivo.', stepLabel: 'Paso', demoEyebrow: 'Demostración visual', demoTitle: 'Mira lo sencillo que es usar la aplicación', helpTitle: 'Si necesitas ayuda inmediata' });
Object.assign(es.support, { eyebrow: 'Apoyo transparente', title: 'Ayuda a axismind a seguir siendo cuidadoso e independiente.', intro: 'El apoyo es voluntario y cualquier cantidad ayuda a mantener el proyecto.', dataTitle: 'Datos para apoyar', securityTitle: 'Seguridad', internationalTitle: 'Apoyo internacional' });
Object.assign(es.security, { eyebrow: 'Privacidad por arquitectura', title: 'Seguridad local, explicada con transparencia.', intro: 'axismind reduce la exposición de los relatos: los datos personales permanecen en el dispositivo.', controlsTitle: 'Controles presentes en la aplicación', resultEyebrow: 'Evaluación automatizada independiente', resultTitle: 'Qué encontró el análisis estático', tool: 'Herramienta utilizada:' });
Object.assign(es.privacy, { title: 'Política de Privacidad', intro: 'Esta política explica cómo la aplicación y este sitio tratan la información.', s1: '1. Responsable y contacto', s2: '2. Qué es axismind', s3: '3. Datos y finalidades', s4: '4. Dónde permanecen los datos', s5: '5. Conexiones externas', s6: '6. Derechos y eliminación', s7: '7. Seguridad y límites', s8: '8. Edad y cambios' });
Object.assign(es.terms, { title: 'Términos de Uso', intro: 'Al usar axismind, confirmas que comprendes la naturaleza personal y local de la herramienta y sus límites.' });
Object.assign(it.how, { eyebrow: 'Guida all’uso', title: 'Inizia con calma e resta al comando.', intro: 'axismind organizza i tuoi appunti personali direttamente sul dispositivo.', stepLabel: 'Passo', demoEyebrow: 'Dimostrazione visiva', demoTitle: 'Scopri quanto è semplice usare l’app', helpTitle: 'Se hai bisogno di aiuto immediato' });
Object.assign(it.support, { eyebrow: 'Supporto trasparente', title: 'Aiuta axismind a restare attento e indipendente.', intro: 'Il supporto è volontario e ogni importo aiuta a mantenere il progetto.', dataTitle: 'Dati per il supporto', securityTitle: 'Sicurezza', internationalTitle: 'Supporto internazionale' });
Object.assign(it.security, { eyebrow: 'Privacy per architettura', title: 'Sicurezza locale, spiegata con trasparenza.', intro: 'axismind riduce l’esposizione dei dati: le informazioni personali restano sul dispositivo.', controlsTitle: 'Controlli presenti nell’app', resultEyebrow: 'Valutazione automatizzata indipendente', resultTitle: 'Cosa ha trovato l’analisi statica', tool: 'Strumento utilizzato:' });
Object.assign(it.privacy, { title: 'Informativa sulla privacy', intro: 'Questa informativa descrive come l’app e questo sito trattano le informazioni.', s1: '1. Titolare e contatti', s2: '2. Che cos’è axismind', s3: '3. Dati e finalità', s4: '4. Dove restano i dati', s5: '5. Connessioni esterne', s6: '6. Diritti e cancellazione', s7: '7. Sicurezza e limiti', s8: '8. Età e modifiche' });
Object.assign(it.terms, { title: 'Termini d’uso', intro: 'Usando axismind, confermi di comprendere la natura personale e locale dello strumento e i suoi limiti.' });
Object.assign(fr.how, { eyebrow: 'Guide d’utilisation', title: 'Commencez doucement et gardez le contrôle.', intro: 'axismind organise vos notes personnelles directement sur l’appareil.', stepLabel: 'Étape', demoEyebrow: 'Démonstration visuelle', demoTitle: 'Découvrez la simplicité de l’application', helpTitle: 'Si vous avez besoin d’une aide immédiate' });
Object.assign(fr.support, { eyebrow: 'Soutien transparent', title: 'Aidez axismind à rester attentif et indépendant.', intro: 'Le soutien est volontaire et chaque contribution aide à maintenir le projet.', dataTitle: 'Informations de soutien', securityTitle: 'Sécurité', internationalTitle: 'Soutien international' });
Object.assign(fr.security, { eyebrow: 'Confidentialité par conception', title: 'Sécurité locale, expliquée en toute transparence.', intro: 'axismind réduit l’exposition des notes : les données personnelles restent sur l’appareil.', controlsTitle: 'Contrôles présents dans l’application', resultEyebrow: 'Évaluation automatisée indépendante', resultTitle: 'Ce que l’analyse statique a trouvé', tool: 'Outil utilisé :' });
Object.assign(fr.privacy, { title: 'Politique de confidentialité', intro: 'Cette politique décrit comment l’application et ce site traitent les informations.', s1: '1. Responsable et contact', s2: '2. Qu’est-ce qu’axismind ?', s3: '3. Données et finalités', s4: '4. Où restent les données', s5: '5. Connexions externes', s6: '6. Droits et suppression', s7: '7. Sécurité et limites', s8: '8. Âge et changements' });
Object.assign(fr.terms, { title: 'Conditions d’utilisation', intro: 'En utilisant axismind, vous confirmez comprendre la nature personnelle et locale de l’outil et ses limites.' });
Object.assign(ru.how, { eyebrow: 'Руководство', title: 'Начните спокойно и сохраняйте контроль.', intro: 'axismind организует личные записи прямо на устройстве.', stepLabel: 'Шаг', demoEyebrow: 'Визуальная демонстрация', demoTitle: 'Посмотрите, как просто пользоваться приложением', helpTitle: 'Если нужна срочная помощь' });
Object.assign(ru.support, { eyebrow: 'Прозрачная поддержка', title: 'Помогите axismind оставаться внимательным и независимым.', dataTitle: 'Данные для поддержки', securityTitle: 'Безопасность', internationalTitle: 'Международная поддержка' });
Object.assign(de.how, { eyebrow: 'Anleitung', title: 'Beginnen Sie in Ruhe und behalten Sie die Kontrolle.', intro: 'axismind organisiert persönliche Einträge direkt auf dem Gerät.', stepLabel: 'Schritt', demoEyebrow: 'Visuelle Demo', demoTitle: 'Sehen Sie, wie einfach die App ist', helpTitle: 'Wenn Sie sofort Hilfe brauchen' });
Object.assign(de.support, { eyebrow: 'Transparente Unterstützung', title: 'Helfen Sie axismind, sorgfältig und unabhängig zu bleiben.', dataTitle: 'Unterstützungsdaten', securityTitle: 'Sicherheit', internationalTitle: 'Internationale Unterstützung' });
Object.assign(zhCN.how, { eyebrow: '使用指南', title: '从容开始，掌握主动权。', intro: 'axismind 直接在设备上整理个人记录。', stepLabel: '步骤', demoEyebrow: '视觉演示', demoTitle: '看看使用应用有多简单', helpTitle: '如果您需要立即帮助' });
Object.assign(zhCN.support, { eyebrow: '透明支持', title: '帮助 axismind 保持谨慎与独立。', dataTitle: '支持信息', securityTitle: '安全', internationalTitle: '国际支持' });
Object.assign(ja.how, { eyebrow: '使い方ガイド', title: 'ゆっくり始めて、自分でコントロールしましょう。', intro: 'axismind は個人の記録を端末上で整理します。', stepLabel: 'ステップ', demoEyebrow: 'ビジュアルデモ', demoTitle: 'アプリの使い方はとても簡単です', helpTitle: 'すぐに助けが必要な場合' });
Object.assign(ja.support, { eyebrow: '透明な支援', title: 'axismind が丁寧で独立した活動を続けられるよう支援してください。', dataTitle: '支援情報', securityTitle: 'セキュリティ', internationalTitle: '海外からの支援' });
Object.assign(ko.how, { eyebrow: '사용 안내', title: '천천히 시작하고 주도권을 유지하세요.', intro: 'axismind는 기기에서 개인 기록을 정리합니다.', stepLabel: '단계', demoEyebrow: '시각적 데모', demoTitle: '앱 사용이 얼마나 간단한지 확인하세요', helpTitle: '즉시 도움이 필요한 경우' });
Object.assign(ko.support, { eyebrow: '투명한 후원', title: 'axismind가 신중하고 독립적으로 운영되도록 도와주세요.', dataTitle: '후원 정보', securityTitle: '보안', internationalTitle: '국제 후원' });
Object.assign(ar.how, { eyebrow: 'دليل الاستخدام', title: 'ابدأ بهدوء وحافظ على تحكمك.', intro: 'ينظّم axismind السجلات الشخصية على الجهاز نفسه.', stepLabel: 'الخطوة', demoEyebrow: 'عرض مرئي', demoTitle: 'تعرّف على سهولة استخدام التطبيق', helpTitle: 'إذا احتجت إلى مساعدة فورية' });
Object.assign(ar.support, { eyebrow: 'دعم شفاف', title: 'ساعد axismind على الاستمرار بعناية واستقلالية.', dataTitle: 'بيانات الدعم', securityTitle: 'الأمان', internationalTitle: 'الدعم الدولي' });
Object.assign(he.how, { eyebrow: 'מדריך שימוש', title: 'התחילו ברוגע ושמרו על השליטה.', intro: 'axismind מארגן רשומות אישיות ישירות במכשיר.', stepLabel: 'שלב', demoEyebrow: 'הדגמה חזותית', demoTitle: 'כך פשוט להשתמש באפליקציה', helpTitle: 'אם אתם זקוקים לעזרה מיידית' });
Object.assign(he.support, { eyebrow: 'תמיכה שקופה', title: 'עזרו ל־axismind להישאר קשוב ועצמאי.', dataTitle: 'פרטי תמיכה', securityTitle: 'אבטחה', internationalTitle: 'תמיכה בינלאומית' });

export const messages: Record<Locale, Messages> = { 'pt-BR': ptBR, en, es, it, fr, ru, de, 'zh-CN': zhCN, ja, ko, ar, he };

export function interpolate(value: string, variables: Record<string, string | number> = {}) {
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(variables[key] ?? `{${key}}`));
}
